# Generated by Django 3.0.4 on 2020-03-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chocie',
            new_name='Choice',
        ),
    ]
